### ISSUE TITLE
No such file or directory: './save/mnist/mlp_iidFalse_num100_C0.1_le1/shard2/run1/dict_users.pkl'

### ISSUE THREAD

**Issue by Wemmy** [pliang279/LG-FedAvg#5]
Hi, thank you for your work. 
I meet the above error when i run it. Do you have any idea?

**Comment by KiteFlyKid** [comment]
I suppose this is because they have already saved dict_users_train,dict_users_test while examing the code
you can  add this  before that error
```python  
    with open(dict_save_path, mode='wb') as handle:
        pickle.dump(obj=(dict_users_train,dict_users_test),file=handle)
```
